# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  branch: 
    description: 'branch'
    default: 'test'
    required: true
  repo: 
    description: 'repo'
    default: 'test'
    required: true
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}