# action.yml
name: 'DocCy'
description: 'run cypress tests in docker'
inputs:
  branch: 
    description: 'branch name'
    required: true
  repo: 
    description: 'repo name'
    required: true
outputs:
  time: # id of output
    description: 'The time we ran the test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.folder }}
    - ${{ inputs.apiUrl }}
    - ${{ inputs.calendlyLink }}
    - ${{ inputs.orthoCalendlyLink }}